### ISSUE TITLE
Erb to Haml conversion fails with spaces in the path

### ISSUE THREAD

**Issue by LarryFransson** [indirect/haml-rails#102]
Running `rails generate haml:application_layout convert` fails if there is a space in any element of the path, e.g. `Users/me/my directory/my_project`.  An error is displayed during the process, but then the success message is also displayed.  Removing the space from the path and running the command again results in success.

**Comment by serv** [comment]
If I reproduce the issues, I'll fix this.

**Comment by serv** [comment]
@indirect this can be closed now

**Comment by indirect** [comment]
:+1:
