### ISSUE TITLE
Excess spaces while rendering multiline string

### ISSUE THREAD

**Issue by atomAltera** [indirect/haml-rails#109]
Hello, today I end up with strange issue in Rails 5:

Here is how a simple _text.html.erb_ file looks like:
`<textarea><%= "a\nb\nc" %></textarea>`
And here is what it produce:
[![enter image description here][1]][1] [![enter image description here][2]][2]

I'm talking about these leading spaces before second and third strings.

In my code I have a form with textarea: 

    .form
      =form_for article do |f|
        .form-group
          =field_label f, :text, true
          =f.text_area :text, class: %w(form-control), rows: 20, placeholder: t('placeholder.article_text')

And the same issue happens there on Edit action

I found out that the reason is haml-rails gem in Gemfile. Without it `<textarea><%= "a\nb\nc" %></textarea>` forks fine, but with it, it adds extra spaces. 

  [1]: http://i.stack.imgur.com/qzTx4.png
  [2]: http://i.stack.imgur.com/Z09F4.png

**Comment by indirect** [comment]
I strongly suspect that it's the Haml gem, and not this gem, which just contains some generators and has a dependency on Haml.

**Comment by atomAltera** [comment]
Ok, thank you. Fortunatly, in production it works fine
