### ISSUE TITLE
%p tag does not work as expected / Chrome

### ISSUE THREAD

**Issue by donmb1** [indirect/haml-rails#110]
I am using this markup in my rails view

```
%p
  %h2 Unser Bier
  %strong Qualität und Geschmack
```

this gets compiled to:

```
<p></p>
<h2>Unser Bier</h2>
<strong>Qualität und Geschmack</strong>
```

Few things noted:
- This only affects my Inspector in Chrome (V 48.0.2564.116)
- When checking the source of my view, it seems to be correctly compiled
- However, the output and what I actually see is wrong
- Same problem in Safari and Firefox

Gemfile.lock

```
haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
```

**Comment by janpapenbrock** [comment]
Probably that's because `<p><h2>Foo</h2></p>` is invalid HTML, and browsers auto-correct it.

See http://stackoverflow.com/a/4676008/1824988
