### ISSUE TITLE
Circular require warning when loading in Rails 5

### ISSUE THREAD

**Issue by ijdickinson** [indirect/haml-rails#117]
I have a Rails engine project that has been running fine under 4.2.3. Attempting to upgrade to Rails 5.0.0.1 today, I get a warning when I run my tests (see long stacktrace below).  What I'm not sure about is whether this was always occurring, and Rails 5 is now more picky about reporting the circularity, or whether it's a change introduced by Rails 5.

My tests still complete, but obviously I'd like to find out what's causing the log noise in case it's indicating a genuine problem.

Stack trace:

    /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293: warning: loading in progress, circular require considered harmful - /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template.rb
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:4:in  `<main>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:4:in  `select'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:9:in  `block in <main>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:9:in  `each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:10:in  `block (2 levels) in <main>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.2.2/lib/rake/rake_test_loader.rb:10:in  `require'
    from /home/ian/workspace/epimorphics/qonsole-rails/test/controllers/qonsole_rails/qonsole_controller_test.rb:1:in  `<top (required)>'
    from /home/ian/workspace/epimorphics/qonsole-rails/test/controllers/qonsole_rails/qonsole_controller_test.rb:1:in  `require'
    from /home/ian/workspace/epimorphics/qonsole-rails/test/test_helper.rb:23:in  `<top (required)>'
    from /home/ian/workspace/epimorphics/qonsole-rails/test/test_helper.rb:23:in  `require'
    from /home/ian/workspace/epimorphics/qonsole-rails/test/dummy/config/environment.rb:5:in  `<top (required)>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in  `method_missing'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in  `public_send'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/application.rb:352:in  `initialize!'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in  `run_initializers'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in  `tsort_each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in  `tsort_each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `each_strongly_connected_component'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `call'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in  `each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in  `block in each_strongly_connected_component'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in  `each_strongly_connected_component_from'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in  `block (2 levels) in each_strongly_connected_component'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in  `block in tsort_each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in  `block in run_initializers'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in  `run'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in  `instance_exec'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/railtie.rb:13:in  `block in <class:Railtie>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/template.rb:3:in  `<top (required)>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:1:in  `<top (required)>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/helpers/action_view_mods.rb:2:in  `<module:ActionView>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:10:in  `<top (required)>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:139:in  `<module:ActionView>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionview-5.0.0.1/lib/action_view/base.rb:215:in  `<class:Base>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in  `run_load_hooks'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in  `each'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:45:in  `block in run_load_hooks'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in  `execute_hook'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in  `instance_eval'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/haml-4.0.7/lib/haml/railtie.rb:5:in  `block (2 levels) in <top (required)>'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in  `load_dependency'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `block in require'
    from /home/ian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in  `require'

**Comment by ijdickinson** [comment]
The issue seems to be this hook that's installed in `railtie.rb`:

    if defined?(ActiveSupport)
      require 'haml/template/options'
      ActiveSupport.on_load(:before_initialize) do
        ActiveSupport.on_load(:action_view) do
          require "haml/template"
        end
      end
    end

This is actually from the `haml` gem, though it's Rails-specific behaviour, so I'm not sure if I should be discussing this issue here or on the haml repo. Anyway, commenting out the `require` in the on-load hook makes the circular warning go away, which makes sense because line 13 in the same file is already loading `haml/template`.

**Comment by indirect** [comment]
I definitely can’t do anything about the haml gem, sorry.

**Comment by ijdickinson** [comment]
Np, I should have closed the issue here myself when I realised the (apparent) root cause. I've logged an issue in the Haml repo https://github.com/haml/haml/issues/883
