### ISSUE TITLE
Stable release version including fix for "hmtl" defect

### ISSUE THREAD

**Issue by matthewlmcclure** [indirect/haml-rails#119]
Hi,

It seems that the most recent release was 0.9.0 in March 2015.

The haml-rails README still recommends using that version.

It seems that version suffers from the "hmtl" defect fixed at <https://github.com/indirect/haml-rails/commit/248c3bb098b45cf465bf333c9912788fe19a725e>.

What is the most stable version including that fix today?

**Comment by serv** [comment]
Good point. I think new update is overdue. There's been many fixes since March 2015, and we should get a new version.
@indirect can we get an update for the gem?

**Comment by syguer** [comment]
v1.0.0 was released on April 27, 2017 🎉
