### ISSUE TITLE
uninitialized constant Haml::Template (NameError)

### ISSUE THREAD

**Issue by jegedeolamide99** [indirect/haml-rails#126]
@indirect 
Please I get this error whenever I run the rails g rails_admin:install  command

`root@kali:~/Desktop/my_fast_cash# rails g rails_admin:install
/var/lib/gems/2.3.0/gems/haml-rails-0.9.0/lib/haml-rails.rb:13:in `block in <class:Railtie>': uninitialized constant Haml::Template (NameError)
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:41:in `execute_hook'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /var/lib/gems/2.3.0/gems/activesupport-5.0.2/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application/bootstrap.rb:78:in `block in <module:Bootstrap>'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /root/Desktop/my_fast_cash/config/environment.rb:5:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
`

Please help me ASAP

**Comment by syguer** [comment]
duplicated with https://github.com/sferik/rails_admin/issues/2855
