### ISSUE TITLE
‘No such file or directory - pandoc’ when trying to use :markdown filter

### ISSUE THREAD

**Issue by humphreybc** [indirect/haml-rails#129]
I am trying to use the [`:markdown`][1] filter with `haml-rails 0.9` on Rails 5.0.2. 

When I first tried to use Markdown in a HAML file, it said it needed `pandoc-ruby` as a dependency, so I added that to my Gemfile. However, now when I try to use `:markdown` inside my file, I am getting the following error:

![screen shot 2017-04-19 at 9 52 34 am](https://cloud.githubusercontent.com/assets/1124253/25157800/deb4c396-24e6-11e7-9a61-ae2357747a38.png)

  [1]: http://haml.info/docs/yardoc/file.REFERENCE.html#markdown-filter

**Comment by syguer** [comment]
@humphreybc 
Is Pandoc installed?
http://pandoc.org/installing.html
