### ISSUE TITLE
rails 6 error: Rails::SourceAnnotationExtractor is not a class/module

### ISSUE THREAD

**Issue by dkuku** [indirect/haml-rails#148]
New project on rails 6 beta throws:
`
.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/haml-rails-1.0.0/lib/haml-rails.rb:49:in 'block in <class:Railtie>': Rails::SourceAnnotationExtractor is not a class/module (TypeError)
`
There was similiar problem with rspec-rails - I had to change the line from 
`SourceAnnotationExtractor::Annotation.register_extensions('haml') do |tag| `
to
`::Rails::SourceAnnotationExtractor::Annotation.register_extensions('haml') do |tag|`
I don't know if this solution is any good to push it upstream but it works for me

**Comment by radar** [comment]
Thank you for reporting this! This will be fixed with #146 and #147. I will also be merging in #150 "soon"*, and then releasing the whole batch as a 2.0 of haml-rails. 

(where "soon" could mean anything from "end of the week" to "end of next month", depending on my availability)

**Comment by prathamesh-sonpatki** [comment]
This can be closed now that https://github.com/indirect/haml-rails/pull/150 is merged.
