### ISSUE TITLE
ActionView::TemplateError Undefined method 'html_tag' for rails 3.2.18

### ISSUE THREAD

**Issue by amolplay** [indirect/haml-rails#156]
When I use `rails server` then it's giving error as : Undefined method 'html_tag' .
It seems haml template views are not rendering.

Used gems: 
haml
haml-rails

Ruby: 1.9.3
Rails: 3.2.18

Also, it's gives undefined method `control_group` when I removed `html_tag `from code base
    = f.control_group :email do |f|
      = f.label :email, :class => "control-label"

When I remove above gems them plain HTML page rendering successfully.....!

I spent several nights but still not able to find out the root cause.
Any help would be appreciated.

**Comment by syguer** [comment]
Newest `haml-rails` requires ruby ` >= 2.3.0` and Rails `>= 5.1`.
By the way, if you cannot update, try [this](https://github.com/indirect/haml-rails#older-versions-of-rails).

**Comment by amolplay** [comment]
I have added following line and bundle installed successfully... 

But still error exists and not able found the solution.. 

gem "haml-rails", "~> 2.0"
