### ISSUE TITLE
Could not find generator haml:application_layout

### ISSUE THREAD

**Issue by ifalvarez** [indirect/haml-rails#75]
rails generate haml:application_layout convert

Gives this error:
Could not find generator haml:application_layout.

**Comment by kkoci** [comment]
Hi, I'm using version 0.7.0, and I got the exact same error, any ideas? I'm on rails v4.2

**Comment by serv** [comment]
@kkoci are you still having the issue?

I tried to reproduce the issue on Rails 4.2 and ruby 2.1.5p273, but no luck.

Can you do the following and show me what you get for each one.

```
$ rails -v
$ ruby -v
$ bundle list
```

**Comment by kkoci** [comment]
Hi, yes, still have the problem.

rails -v : 4.2.0
ruby -v : 2.0.0p195

bundle list:

Gems included by the bundle:
  * actionmailer (4.2.0)
  * actionpack (4.2.0)
  * actionview (4.2.0)
  * activeadmin (1.0.0.pre 1eda0b7)
  * activejob (4.2.0)
  * activemodel (4.2.0)
  * activerecord (4.2.0)
  * activesupport (4.2.0)
  * arbre (1.0.3)
  * arel (6.0.0)
  * bcrypt (3.1.9)
  * binding_of_caller (0.7.2)
  * bourbon (4.1.1)
  * builder (3.2.2)
  * bundler (1.7.9)
  * byebug (3.5.1)
  * coffee-rails (4.1.0)
  * coffee-script (2.3.0)
  * coffee-script-source (1.8.0)
  * columnize (0.9.0)
  * debug_inspector (0.0.2)
  * debugger-linecache (1.2.0)
  * devise (3.4.1)
  * erubis (2.7.0)
  * execjs (2.2.2)
  * formtastic (3.1.3)
  * formtastic_i18n (0.1.1)
  * globalid (0.3.0)
  * haml (4.1.0.beta.1)
  * haml-rails (0.7.0)
  * has_scope (0.6.0.rc)
  * hike (1.2.3)
  * hpricot (0.8.6)
  * html2haml (1.0.1)
  * i18n (0.7.0)
  * inherited_resources (1.5.1 ff1c991)
  * jbuilder (2.2.6)
  * jquery-rails (4.0.3)
  * jquery-ui-rails (5.0.3)
  * json (1.8.2)
  * kaminari (0.16.1)
  * loofah (2.0.1)
  * mail (2.6.3)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.5.1)
  * multi_json (1.10.1)
  * nokogiri (1.6.5)
  * orm_adapter (0.5.0)
  * polyamorous (1.1.0)
  * rack (1.6.0)
  * rack-test (0.6.3)
  * rails (4.2.0)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.5)
  * rails-html-sanitizer (1.0.1)
  * railties (4.2.0)
  * rake (10.4.2)
  * ransack (1.6.2)
  * rdoc (4.2.0)
  * responders (2.0.2)
  * ruby_parser (3.1.3)
  * sass (3.4.10)
  * sass-rails (5.0.1)
  * sdoc (0.4.1)
  * sexp_processor (4.4.5)
  * slop (3.6.0)
  * sprockets (2.12.3)
  * sprockets-rails (2.2.2)
  * sqlite3 (1.3.10)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * tzinfo-data (1.2014.10)
  * uglifier (2.7.0)
  * warden (1.2.3)
  * web-console (2.0.0)

Any ideas?

**Comment by sedx** [comment]
same problem with rake tasks :(

**Comment by kkoci** [comment]
Hello? :( still nothing here

**Comment by sedx** [comment]
@kkoci I send PR https://github.com/indirect/haml-rails/pull/81
you can try it

**Comment by derricklannaman** [comment]
Had the same issue. Had to update haml-rails from haml-rails-0.5.3. Then I got error:

`There is a version mismatch between the spring client and the server.`
`You should restart the server and make sure to use the same version.`

`CLIENT: 1.3.0, SERVER: 1.2.0`

Stop server. Run `spring stop`. Restart server.

Rerun `rails generate haml:application_layout convert`
That worked for me

**Comment by rusikf** [comment]
Everything is works now, just run ```rails g haml:application_layout```

**Comment by kkoci** [comment]
Awesome! Thank you!

On Fri, May 1, 2015 at 4:39 PM, Ruslan Korolev <notifications@github.com>
wrote:

> Everything is works now, just run rails g haml:application_layout
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/indirect/haml-rails/issues/75#issuecomment-98239491>.
>



-- 
Kristian Koci
Linux User #582221
Website: http://tuespacioweb.com.ve
Cel. 0416 202 92 94

   <http://twitfooter.com/twitter/view/kkoci80>
 <http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
<http://twitfooter.com/twitter/view/kkoci80>
