### ISSUE TITLE
Broken template after erb2haml

### ISSUE THREAD

**Issue by lancedikson** [indirect/haml-rails#88]
Hi! I just ran ```rake haml:erb2haml``` for all .erb files. There was three erb files in one directory:
```
login
|- index.html.erb
|- login.html.erb
|- logout.html.erb
```
CLI asked me about what files I wanna convert.
Now, I have the same files, but in haml-format. But, one of those (login.html.haml) looks like this:
```
\%h1 Login#index
\%p Find me in app/views/login/index.html.erb
```
I don't know why these lines prefixed by backslash. Is it bug?

**Comment by indirect** [comment]
No idea. :) Feel free to investigate!

**Comment by sedx** [comment]
@lancedikson it's look like `html2haml` gem problem, because file conversion his job
```ruby
`html2haml #{file} #{file.gsub(/\.erb\z/, '.haml')}`
```

**Comment by rusikf** [comment]
@lancedikson, It is a problem with ```html2haml``` gem ,as noted @sedx. You can create issue for it here https://github.com/haml/html2haml
