### ISSUE TITLE
documentation for changing haml implementations (e.g. using hamlit )

### ISSUE THREAD

**Issue by ivar** [indirect/haml-rails#96]
The [Hamlit](https://github.com/k0kubun/hamlit) gem seems to be the new torch bearer for HAML lovers. The haml-rails gem should provide instructions on how to swap/upgrade.

**Comment by ivar** [comment]
hmm.. the only hook to actual the stock `haml` gem I could find is on https://github.com/indirect/haml-rails/blob/master/haml-rails.gemspec#L18

**Comment by indirect** [comment]
You could always release hamlit-rails...

**Comment by mfung** [comment]
Here's a start: 
https://github.com/mfung/hamlit-rails
I excluded some of the niceties of haml-rails because html2haml requires haml.
